# Generated by Django 5.2.3 on 2025-12-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_email_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_sms_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
