"""
Recommendation model for storing crop recommendations.
"""
from django.db import models
from soil.models import SoilInput


class Recommendation(models.Model):
    """
    Model to store crop recommendations generated by the ML model.
    
    Fields:
    - input: Related soil input data
    - crop_name: Recommended crop
    - explanation: XAI-generated explanation
    - created_at: Timestamp of recommendation
    """
    
    input = models.ForeignKey(
        SoilInput,
        on_delete=models.CASCADE,
        related_name='recommendations'
    )
    crop_name = models.CharField(max_length=100, help_text='Recommended crop name')
    explanation = models.TextField(help_text='XAI explanation for the recommendation')
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'recommendations'
        ordering = ['-created_at']
        verbose_name = 'Recommendation'
        verbose_name_plural = 'Recommendations'
    
    def __str__(self):
        return f"{self.crop_name} - {self.input.user.username} - {self.created_at.strftime('%Y-%m-%d')}"
