# Generated by Django 4.2.7 on 2025-11-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Model algorithm name', max_length=100)),
                ('version', models.CharField(help_text='Model version', max_length=50)),
                ('accuracy', models.FloatField(help_text='Model accuracy score')),
                ('file_path', models.CharField(help_text='Path to saved model file', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Model Registry',
                'verbose_name_plural': 'Model Registry',
                'db_table': 'model_registry',
                'ordering': ['-created_at'],
            },
        ),
    ]
