# Generated by Django 4.2.7 on 2025-11-24 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(help_text='Recommended crop name', max_length=100)),
                ('explanation', models.TextField(help_text='XAI explanation for the recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='soil.soilinput')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'db_table': 'recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
