# Generated by Django 4.2.7 on 2025-11-24 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_level', models.FloatField(help_text='Nitrogen content in mg/kg')),
                ('P_level', models.FloatField(help_text='Phosphorus content in mg/kg')),
                ('K_level', models.FloatField(help_text='Potassium content in mg/kg')),
                ('ph', models.FloatField(help_text='Soil pH level (0-14)')),
                ('moisture', models.FloatField(help_text='Soil moisture percentage (0-100%)')),
                ('temperature', models.FloatField(help_text='Soil temperature in Celsius')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_inputs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soil Input',
                'verbose_name_plural': 'Soil Inputs',
                'db_table': 'soil_inputs',
                'ordering': ['-created_at'],
            },
        ),
    ]
