# Generated by Django 5.2.3 on 2025-12-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilinput',
            name='integrity_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash for data integrity verification', max_length=64, null=True),
        ),
    ]
