# Generated by Django 5.2.3 on 2025-12-08 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city', models.CharField(blank=True, max_length=100)),
                ('forecast_date', models.DateField()),
                ('temperature_min', models.FloatField()),
                ('temperature_max', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('condition', models.CharField(max_length=200)),
                ('rain_probability', models.FloatField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forecast Log',
                'verbose_name_plural': 'Forecast Logs',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('heat_warning', 'Heat Warning'), ('cold_warning', 'Cold Warning'), ('rain_alert', 'Rain Alert'), ('storm_warning', 'Storm Warning'), ('humidity_warning', 'Humidity Warning'), ('wind_warning', 'Wind Warning'), ('drought_risk', 'Drought Risk'), ('frost_warning', 'Frost Warning')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weather Alert',
                'verbose_name_plural': 'Weather Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='MY', max_length=50)),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField(blank=True, null=True)),
                ('humidity', models.IntegerField()),
                ('pressure', models.IntegerField(blank=True, null=True)),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=200)),
                ('weather_icon', models.CharField(blank=True, max_length=10)),
                ('clouds', models.IntegerField(default=0)),
                ('visibility', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('weather_timestamp', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weather Log',
                'verbose_name_plural': 'Weather Logs',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
