# Generated by Django 5.2.3 on 2025-12-08 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_latitude', models.FloatField()),
                ('search_longitude', models.FloatField()),
                ('search_radius', models.IntegerField(default=10000)),
                ('markets_found', models.IntegerField(default=0)),
                ('buyers_found', models.IntegerField(default=0)),
                ('stores_found', models.IntegerField(default=0)),
                ('total_results', models.IntegerField(default=0)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Market Search',
                'verbose_name_plural': 'Market Searches',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=100)),
                ('place_name', models.CharField(max_length=200)),
                ('place_type', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Place Visit',
                'verbose_name_plural': 'Place Visits',
                'ordering': ['-visited_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoritePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('place_type', models.CharField(choices=[('market', 'Market'), ('buyer', 'Buyer'), ('agri_store', 'Agricultural Store')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_visited', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Place',
                'verbose_name_plural': 'Favorite Places',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'place_id')},
            },
        ),
    ]
